// Prompt Manager - Handles all Would You Rather prompts
// 1000+ Premium Prompts with Clear Opposing Choices
class PromptManager {
    constructor() {
        // Random selection is automatic - getRandomPrompts() picks random prompts each time
        this.defaultPrompts = [
            // Classic Choices - Fun, everyday decisions
            ['Pizza', 'Burger'],
            ['Coffee', 'Tea'],
            ['Beach', 'Mountains'],
            ['Summer', 'Winter'],
            ['Dog', 'Cat'],
            ['Books', 'Movies'],
            ['Morning Person', 'Night Owl'],
            ['City Life', 'Country Life'],
            ['Swimming', 'Hiking'],
            ['Chocolate', 'Vanilla'],
            ['Flying', 'Invisibility'],
            ['Time Travel to Past', 'Time Travel to Future'],
            ['Be Rich', 'Be Famous'],
            ['Always Hot', 'Always Cold'],
            ['Sweet Snacks', 'Salty Snacks'],
            ['Netflix at Home', 'Movie Theater'],
            ['Wake Up Early', 'Stay Up Late'],
            ['Travel the World', 'Stay Home'],
            ['Android', 'iPhone'],
            ['Reading Books', 'Writing Stories'],

            // Technology & Social Media - Modern digital life
            ['Instagram', 'TikTok'],
            ['YouTube', 'Twitch'],
            ['Twitter', 'Reddit'],
            ['PlayStation', 'Xbox'],
            ['Gaming PC', 'Gaming Console'],
            ['Wireless Earbuds', 'Over-Ear Headphones'],
            ['Smart Watch', 'Traditional Watch'],
            ['Laptop', 'Desktop Computer'],
            ['Mac', 'Windows PC'],
            ['Alexa', 'Google Home'],
            ['Virtual Reality', 'Real Life'],
            ['Electric Car', 'Gas Car'],
            ['Self-Driving Car', 'Drive Yourself'],
            ['Latest Smartphone', 'Reliable Old Phone'],
            ['Tablet', 'Laptop'],
            ['Spotify', 'Apple Music'],
            ['Smart Home', 'Traditional Home'],
            ['Online Shopping', 'In-Store Shopping'],
            ['Video Call', 'Voice Call'],
            ['Text Messages', 'Phone Calls'],
            ['Dark Mode', 'Light Mode'],
            ['Send GIFs', 'Send Emojis'],
            ['Watch Memes', 'Watch Videos'],
            ['Listen to Podcasts', 'Listen to Audiobooks'],
            ['AI Do Your Work', 'Do It Yourself'],
            ['Bitcoin', 'Cash Money'],
            ['Buy NFTs', 'Buy Physical Art'],
            ['Cloud Storage', 'External Hard Drive'],
            ['Wireless Charging', 'Fast Cable Charging'],
            ['5G Speed', 'Unlimited 4G Data'],

            // Food & Drinks - Delicious dilemmas
            ['Tacos', 'Burritos'],
            ['Sushi', 'Ramen'],
            ['Italian Food', 'Chinese Food'],
            ['Ice Cream', 'Frozen Yogurt'],
            ['Fresh Donuts', 'Warm Cookies'],
            ['Birthday Cake', 'Homemade Pie'],
            ['Potato Chips', 'Buttered Popcorn'],
            ['Juicy Steak', 'Grilled Chicken'],
            ['Breakfast for Dinner', 'Dinner for Breakfast'],
            ['Fluffy Pancakes', 'Crispy Waffles'],
            ['Fruit Smoothie', 'Chocolate Milkshake'],
            ['Energy Drinks', 'Strong Coffee'],
            ['Ice Cold Water', 'Fresh Juice'],
            ['Red Wine', 'Cold Beer'],
            ['Fancy Cocktails', 'Simple Drinks'],
            ['Extremely Spicy', 'Super Mild'],
            ['Asian Cuisine', 'Mexican Food'],
            ['Fast Food', 'Home Cooked'],
            ['All You Can Eat Buffet', 'Fine Dining'],
            ['Cereal and Milk', 'Eggs and Toast'],
            ['Fresh Salad', 'Hot Soup'],
            ['Sandwich', 'Burrito Wrap'],
            ['Hot Dog', 'Cheeseburger'],
            ['French Fries', 'Onion Rings'],
            ['Ketchup on Everything', 'Mayo on Everything'],
            ['Extra Mayo', 'Extra Hot Sauce'],
            ['Peanut Butter', 'Chocolate Spread'],
            ['Fresh Squeezed Juice', 'Bottled Juice'],
            ['Bubble Tea', 'Regular Tea'],
            ['Extra Cheese', 'No Cheese'],
            ['Pizza with Pineapple', 'Pizza Without Pineapple'],
            ['Thin Crust Pizza', 'Deep Dish Pizza'],
            ['Veggie Burger', 'Beef Burger'],
            ['Vegan Diet', 'Keto Diet'],
            ['Eat Healthy Always', 'Eat Whatever You Want'],
            ['Never Drink Alcohol', 'Drink Socially'],
            ['Dessert First', 'Never Eat Dessert'],
            ['Cook Every Meal', 'Order Delivery Every Day'],
            ['Meal Prep Weekly', 'Cook Fresh Daily'],
            ['Drink Only Water', 'Drink Only Soda'],

            // Superpowers & Abilities - Dream powers
            ['Time Travel', 'Teleportation'],
            ['Read Minds', 'Control Minds'],
            ['Super Strength', 'Super Speed'],
            ['Shapeshift into Anyone', 'Move Things with Mind'],
            ['Heal Any Injury', 'Never Die'],
            ['Control Fire', 'Control Water'],
            ['Control Weather', 'Talk to Animals'],
            ['X-Ray Vision', 'Night Vision'],
            ['Talk to Animals', 'Talk to Plants'],
            ['Never Need Sleep', 'Never Need Food'],
            ['Photographic Memory', 'Never Forget Anything'],
            ['Super Intelligence', 'Extreme Charisma'],
            ['Breathe Underwater', 'Survive in Space'],
            ['Hack Any Computer', 'Read Any Mind'],
            ['See the Future', 'Change the Past'],
            ['Be a Wizard', 'Be a Superhero'],
            ['Own a Dragon', 'Own a Phoenix'],
            ['Turn Things to Gold', 'Create Magic Spells'],
            ['Freeze Time', 'Rewind Time'],
            ['Clone Yourself', 'Transform into Anyone'],
            ['Super Hearing', 'Super Smell'],
            ['Walk Through Walls', 'Turn Invisible'],
            ['Never Age', 'Age Backwards'],
            ['Perfect Music Pitch', 'Perfect Memory'],
            ['Speak Every Language', 'Play Every Instrument'],
            ['Paint Like Da Vinci', 'Sing Like Beyoncé'],
            ['Unlimited Energy', 'Unlimited Strength'],
            ['Control Lightning', 'Control Metal'],
            ['Always Know Truth', 'Always Tell Lies'],
            ['Control Your Dreams', 'Control Reality'],
            ['Fly Like Superman', 'Swing Like Spider-Man'],
            ['Laser Eyes', 'Diamond Skin'],
            ['Grow to Giant Size', 'Shrink to Tiny Size'],
            ['Communicate with Dead', 'See Ghosts'],
            ['Super Reflexes', 'Predict Danger'],
            ['Regenerate Like Deadpool', 'Never Get Hurt'],
            ['Create Force Fields', 'Shoot Energy Blasts'],
            ['Run on Water', 'Walk on Air'],
            ['Freeze Anything', 'Melt Anything'],
            ['Create Portals', 'Shadow Travel'],

            // Money & Career - Financial choices
            ['$1 Million Right Now', '$10k Every Month Forever'],
            ['Dream Job Low Salary', 'Boring Job High Salary'],
            ['Work from Home', 'Work from Office'],
            ['4 Day Work Week', '2 Hour Work Days'],
            ['Be Your Own Boss', 'Work for Dream Company'],
            ['Fixed Salary', '100% Commission'],
            ['Job Security Forever', 'High Risk High Reward'],
            ['Follow Your Passion', 'Follow the Money'],
            ['Work Remote Anywhere', 'Amazing Office Environment'],
            ['Retire at 40', 'Work You Love Until 80'],
            ['Start Your Own Company', 'Become CEO of Big Company'],
            ['Freelance Freedom', 'Corporate Benefits'],
            ['Multiple Income Streams', 'One High Paying Job'],
            ['Invest in Stocks', 'Invest in Real Estate'],
            ['Save Every Dollar', 'Enjoy Life Now'],
            ['Buy Luxury Items', 'Travel the World'],
            ['Big House Small Savings', 'Tiny House Big Savings'],
            ['New Sports Car', 'Smart Investments'],
            ['Designer Wardrobe', 'Latest Tech Gadgets'],
            ['Rolex Watch', 'iPhone Pro Max'],
            ['Fly Private Jet Once', 'First Class Forever'],
            ['Own a Yacht', 'Own Private Island'],
            ['Mansion in Suburbs', 'Penthouse Downtown'],
            ['Personal Chef Daily', 'Personal Trainer Daily'],
            ['Financial Advisor', 'Life Coach'],
            ['Win $10M Lottery', 'Inherit $50M'],
            ['Get Paid to Sleep', 'Get Paid to Eat'],
            ['Get Paid to Travel', 'Get Paid to Play Games'],
            ['Unlimited Travel Budget', 'Unlimited Food Budget'],
            ['Free Gas Forever', 'Free Groceries Forever'],
            ['Never Pay Rent', 'Never Pay for Food'],
            ['Win Lottery Today', 'Earn It Slowly'],
            ['Have $1 Billion', 'Perfect Health Forever'],
            ['Rich But Alone', 'Poor But Loved'],
            ['Money Can\'t Buy Happiness', 'Money Solves Everything'],
            ['Debt Free Life', 'Luxury Life with Debt'],
            ['Minimum Wage Happy Job', 'Six Figures Miserable Job'],
            ['Entrepreneur Risk', 'Employee Security'],
            ['Passive Income', 'Active High Income'],
            ['Financial Freedom at 30', 'Work Until 65'],

            // Lifestyle & Leisure - How you live
            ['Party Every Weekend', 'Relax at Home'],
            ['Loud Concert', 'Music Festival'],
            ['Roller Coasters', 'Water Slides'],
            ['Rough Camping', 'Luxury Glamping'],
            ['Epic Road Trip', 'Quick Flight'],
            ['Ocean Cruise', 'Beach Resort'],
            ['Backpack Adventure', '5-Star Hotels'],
            ['Solo Travel', 'Group Vacation'],
            ['Extreme Adventures', 'Peaceful Relaxation'],
            ['Art Museum', 'Theme Park'],
            ['Stadium Sports Game', 'Watch on Couch'],
            ['Play the Sport', 'Watch the Sport'],
            ['Gym Workout', 'Home Exercise'],
            ['Hot Yoga', 'Pilates Class'],
            ['Marathon Running', 'Casual Cycling'],
            ['Ocean Swimming', 'Wave Surfing'],
            ['Snow Skiing', 'Snowboarding'],
            ['Indoor Climbing', 'Outdoor Skydiving'],
            ['Bungee Jump', 'Paraglide'],
            ['Deep Scuba Dive', 'Surface Snorkel'],
            ['Massage Spa Day', 'Sunny Beach Day'],
            ['Shopping Spree', 'Staycation Weekend'],
            ['Dance Nightclub', 'Chill Rooftop Bar'],
            ['Stand-Up Comedy', 'Magic Show'],
            ['Broadway Theater', 'Opera House'],
            ['Modern Art Gallery', 'Science Museum'],
            ['City Zoo', 'Ocean Aquarium'],
            ['Puzzle Escape Room', 'Action Laser Tag'],
            ['Bowling Alley', 'Mini Golf'],
            ['Karaoke Night', 'Trivia Competition'],
            ['Sunrise Hike', 'Sunset Beach'],
            ['Mountain Peak', 'Ocean Depths'],
            ['Desert Safari', 'Jungle Trek'],
            ['Northern Lights', 'Tropical Paradise'],
            ['European Cities', 'Asian Adventures'],
            ['African Safari', 'South American Jungle'],
            ['Australian Outback', 'New Zealand Nature'],
            ['Visit 50 Countries', 'Deep Dive 5 Countries'],
            ['Tourist Attractions', 'Local Hidden Gems'],
            ['Guided Tour', 'Explore Alone'],

            // Relationships & Social - Love and friendship
            ['100 Acquaintances', '5 Best Friends'],
            ['Big Fancy Wedding', 'Intimate Elopement'],
            ['Live Together First', 'Wait for Marriage'],
            ['Have Kids at 25', 'Have Kids at 40'],
            ['Big Extended Family', 'Small Nuclear Family'],
            ['Date Mutual Friend', 'Date Complete Stranger'],
            ['Long Distance Love', 'See Them Daily'],
            ['Meet Family First', 'Meet Friends First'],
            ['Receive Compliments', 'Acts of Service'],
            ['Quality Time Together', 'Physical Affection'],
            ['Surprise Romantic Dates', 'Carefully Planned Dates'],
            ['Cozy Night In', 'Fancy Date Out'],
            ['Dinner and Movie', 'Adventure Activity'],
            ['Adrenaline Date', 'Relaxing Date'],
            ['Double Dates', 'Just You Two'],
            ['Text Throughout Day', 'Call Every Night'],
            ['Post Relationship Online', 'Keep It Private'],
            ['Adopt Pet Together', 'Grow Plants Together'],
            ['Cook Meals Together', 'Order Takeout Together'],
            ['Binge Series Together', 'Read Books Separately'],
            ['Gym Workout Partners', 'Spa Relaxation Together'],
            ['Travel World Together', 'Separate Hobbies'],
            ['Shared Friend Circle', 'Individual Friends'],
            ['Share Everything', 'Maintain Privacy'],
            ['Live Near Family', 'Live Far Away'],
            ['Celebrate Every Holiday', 'Skip All Celebrations'],
            ['Matching Couple Outfits', 'Individual Styles'],
            ['Joint Instagram Account', 'Separate Social Media'],
            ['Know All Passwords', 'Respect Privacy'],
            ['Attached at Hip', 'Healthy Independence'],
            ['Say I Love You Daily', 'Show It with Actions'],
            ['Morning Person Partner', 'Night Owl Partner'],
            ['Introvert Partner', 'Extrovert Partner'],
            ['Adventurous Partner', 'Homebody Partner'],
            ['Spontaneous Partner', 'Organized Planner'],
            ['Creative Artistic Partner', 'Logical Practical Partner'],
            ['Same Career Field', 'Totally Different Jobs'],
            ['Equal Earnings', 'One Earns Much More'],
            ['Traditional Gender Roles', 'Modern Equal Partnership'],
            ['Big Age Gap', 'Same Age'],

            // Entertainment & Pop Culture - Media and entertainment
            ['Marvel Movies', 'DC Comics'],
            ['Star Wars', 'Star Trek'],
            ['Harry Potter', 'Lord of the Rings'],
            ['Disney Classics', 'Pixar Films'],
            ['Scary Horror', 'Funny Comedy'],
            ['Action Explosions', 'Romantic Drama'],
            ['Drama Series', 'Comedy Sitcom'],
            ['Reality TV Shows', 'Educational Documentaries'],
            ['American Cartoons', 'Japanese Anime'],
            ['Read Subtitles', 'Watch Dubbed'],
            ['Buy Theater Popcorn', 'Sneak In Snacks'],
            ['Opening Night Premiere', 'Wait for Streaming'],
            ['Binge Entire Season', 'Watch Weekly Episodes'],
            ['Classic Old Films', 'New Releases'],
            ['Blockbuster Hit', 'Indie Art Film'],
            ['Read Book First', 'Watch Movie First'],
            ['Fiction Novels', 'Non-Fiction Books'],
            ['Physical Paper Books', 'Digital E-Books'],
            ['Public Library', 'Buy at Bookstore'],
            ['Short Story Collections', 'Long Novel Series'],
            ['Celebrity Biography', 'Historical Autobiography'],
            ['Emotional Poetry', 'Dense Prose'],
            ['Graphic Novel Comics', 'Traditional Comics'],
            ['Fashion Magazine', 'News Newspaper'],
            ['Sci-Fi Space Opera', 'Fantasy Magic World'],
            ['Murder Mystery', 'Psychological Thriller'],
            ['Historical Past Fiction', 'Modern Contemporary'],
            ['Stand-Up Comedy Special', 'Silly Sitcom'],
            ['Late Night Talk Show', 'Morning News Show'],
            ['Watch Award Ceremony', 'Skip the Awards'],
            ['Follow Celebrity Gossip', 'Ignore Famous People'],
            ['Comic Con Convention', 'Book Fair'],
            ['Collect Merchandise', 'No Memorabilia'],
            ['Movie Soundtrack', 'Broadway Musical'],
            ['Watch Sports Live', 'Watch Highlights Later'],
            ['Play Video Games', 'Watch Gameplay'],
            ['Create Art', 'Appreciate Art'],
            ['Write Stories', 'Read Stories'],
            ['Make Music', 'Listen to Music'],
            ['Direct Movies', 'Act in Movies'],

            // Gaming & Esports - For gamers
            ['Single Player Story', 'Online Multiplayer'],
            ['Campaign Story Mode', 'Infinite Endless Mode'],
            ['Role-Playing RPG', 'First Person Shooter'],
            ['Open World Explore', 'Linear Story Path'],
            ['Mobile Phone Games', 'Console Gaming'],
            ['Casual Fun Games', 'Competitive Ranked'],
            ['Small Indie Games', 'Big AAA Games'],
            ['Classic Retro Games', 'Latest Modern Games'],
            ['Handheld Controller', 'Keyboard and Mouse'],
            ['Physical Game Disc', 'Digital Download'],
            ['Pre-Order Immediately', 'Wait for Reviews'],
            ['Day One Release', 'Wait for Sale'],
            ['Finish Every Game', 'Try Many Games'],
            ['Main Story Only', '100% Perfect Completion'],
            ['Strategic Planning', 'Fast Action'],
            ['Brain Puzzle Games', 'Speed Racing Games'],
            ['Fighting Versus', 'Team Sports Games'],
            ['Life Simulation', 'Adventure Exploration'],
            ['Battle Royale Survival', 'Team Capture Flag'],
            ['League of Legends', 'Dota 2'],
            ['Fortnite', 'Apex Legends'],
            ['Call of Duty', 'Battlefield'],
            ['Minecraft Creative', 'Minecraft Survival'],
            ['Pokemon Trainer', 'Digimon Tamer'],
            ['Nintendo Switch', 'Steam Deck'],
            ['VR Headset Gaming', 'Traditional Screen'],
            ['Gaming Chair Setup', 'Couch Gaming'],
            ['RGB Lighting Everything', 'Clean Minimal Setup'],
            ['Mechanical Keyboard', 'Silent Membrane'],
            ['Streaming Your Gameplay', 'Gaming Privately'],
            ['Join Gaming Clan', 'Solo Player Only'],
            ['Watch Esports Tournaments', 'Play Casually'],
            ['Grinding for Levels', 'Cheat Codes'],
            ['Hard Difficulty Challenge', 'Easy Relaxed Mode'],
            ['Permadeath Hardcore', 'Multiple Lives Easy'],
            ['PvP Player Combat', 'PvE Monster Fighting'],
            ['Free-to-Play Games', 'Pay Once Games'],
            ['In-Game Purchases', 'Earn Everything'],
            ['Loot Box Gambling', 'Direct Purchase'],
            ['Subscription Service', 'Own Games Forever'],

            // Fashion & Style - Personal style
            ['Designer Brand Clothing', 'Thrift Store Finds'],
            ['Fast Fashion Trends', 'Sustainable Ethical'],
            ['Follow Trends', 'Timeless Classic'],
            ['Comfort Over Style', 'Style Over Comfort'],
            ['Fresh Sneakers', 'Polished Dress Shoes'],
            ['Casual Jeans', 'Comfy Sweatpants'],
            ['Graphic T-Shirts', 'Plain Button-Ups'],
            ['Warm Hoodie', 'Stylish Jacket'],
            ['Elegant Dress', 'Trendy Jumpsuit'],
            ['High Heels', 'Comfortable Flats'],
            ['Full Makeup Daily', 'Natural Look'],
            ['Long Flowing Hair', 'Short Practical Cut'],
            ['Styled Beard', 'Clean Shaven'],
            ['Body Tattoos', 'Clear Skin'],
            ['Multiple Piercings', 'No Piercings'],
            ['Rainbow Wardrobe', 'Black and White'],
            ['Accessorize Everything', 'Pure Minimalist'],
            ['Show Brand Logos', 'No Logo Clothing'],
            ['Vintage Retro Style', 'Ultra Modern Fashion'],
            ['Urban Streetwear', 'Professional Business'],
            ['Athletic Activewear', 'Smart Casual'],
            ['Formal Suit Daily', 'Pajamas All Day'],
            ['Fashion Risk Taker', 'Safe Dresser'],
            ['Seasonal Wardrobe Update', 'Same Clothes Years'],
            ['Matching Outfit Sets', 'Mix and Match'],
            ['Designer Handbag', 'Practical Backpack'],
            ['Luxury Jewelry', 'No Accessories'],
            ['Wear Bright Colors', 'Wear Dark Colors'],
            ['Dress for Others', 'Dress for Yourself'],
            ['Follow Fashion Influencers', 'Ignore Trends'],

            // Education & Learning - School and knowledge
            ['Online College Courses', 'Traditional Campus'],
            ['Liberal Arts Degree', 'STEM Degree'],
            ['Trade Technical School', 'University Bachelor'],
            ['Self-Taught Skills', 'Formal Education'],
            ['Study Alone Quietly', 'Study Group Sessions'],
            ['Early Morning Classes', 'Late Evening Classes'],
            ['Live on Campus', 'Commute from Home'],
            ['Large State University', 'Small Private College'],
            ['Paid Internship', 'Part-Time Job'],
            ['Study Abroad Year', 'Stay Local'],
            ['Heavy Textbooks', 'Online Resources'],
            ['Handwritten Notes', 'Record Lectures'],
            ['Paper and Pen', 'Laptop Typing'],
            ['Colorful Highlighters', 'Sticky Note System'],
            ['Coffee While Studying', 'Tea While Learning'],
            ['Quiet Library Study', 'Busy Cafe Study'],
            ['Music While Working', 'Complete Silence'],
            ['Last Minute Cramming', 'Consistent Daily Study'],
            ['Multiple Choice Tests', 'Written Essay Exams'],
            ['Group Project Work', 'Individual Solo Project'],
            ['Public Speaking Class', 'Written Reports Only'],
            ['Math and Science', 'Arts and Humanities'],
            ['Business School', 'Medical School'],
            ['Law Degree', 'Engineering Degree'],
            ['Psychology Major', 'Computer Science'],
            ['Learn Programming', 'Learn Languages'],
            ['Master\'s Degree', 'Work Experience'],
            ['PhD Research', 'Professional Career'],
            ['Student Loan Debt', 'Work Through School'],
            ['Ivy League School', 'State School Free'],

            // Philosophical & Deep - Thought-provoking
            ['Always 5 Minutes Early', 'Always 5 Minutes Late'],
            ['Know How You Die', 'Know When You Die'],
            ['Restart Life from Birth', 'Continue from Now'],
            ['Edit Your Past', 'See Your Future'],
            ['$100k Debt Dream Life', 'Debt Free Average'],
            ['Live 1000 Years', 'Live 10 Different Lives'],
            ['Look 10 Years Younger', 'Feel 10 Years Younger'],
            ['Know All Answers', 'Ask All Questions'],
            ['World Peace Forever', 'End World Hunger'],
            ['Stop Climate Change', 'Cure All Disease'],
            ['Rewind Age to 18', 'Fast Forward to 65'],
            ['Perfect Memory', 'Forget Bad Memories'],
            ['Always Be Right', 'Always Be Happy'],
            ['Everyone Loves You', 'You Love Everyone'],
            ['Read Faster', 'Remember More'],
            ['Sleep 4 Hours Feel Great', 'Sleep 12 Hours Daily'],
            ['Never Feel Pain', 'Never Feel Sadness'],
            ['Control Emotions', 'Feel Everything Deeply'],
            ['Be Most Attractive', 'Be Most Intelligent'],
            ['Perfect Body No Effort', 'Perfect Mind No Study'],
            ['Eternal Youth', 'Infinite Wisdom'],
            ['Famous Worldwide', 'Anonymous Peaceful'],
            ['Make History', 'Enjoy Present'],
            ['Leave Legacy', 'Live Fully Now'],
            ['Be Remembered Forever', 'Die Unknown Happy'],
            ['Change One Past Decision', 'Know One Future Event'],
            ['Have No Regrets', 'Learn from Mistakes'],
            ['Perfect Life Simulation', 'Imperfect Real Life'],
            ['Live in Past Era', 'Live in Future Era'],
            ['Meet Historical Figure', 'Meet Future Self'],
            ['Witness History', 'Make History'],
            ['Have All Skills', 'Master One Skill'],
            ['Jack of All Trades', 'Master of One'],
            ['Be Extremely Talented', 'Be Extremely Hardworking'],
            ['Natural Born Genius', 'Dedicated Hard Worker'],
            ['Lucky All Life', 'Create Own Success'],
            ['Easy Mode Life', 'Challenging Rewarding Life'],
            ['No Responsibilities', 'Purpose and Meaning'],
            ['Complete Freedom', 'Loving Community'],
            ['Unlimited Free Time', 'Fulfilling Busy Schedule'],
            ['Receive Everything', 'Earn Everything'],

            // Personality & Values - Who you are
            ['Speak Truth Always', 'White Lies Allowed'],
            ['Brutally Honest', 'Tactfully Kind'],
            ['Logic Over Emotion', 'Emotion Over Logic'],
            ['Optimistic Positive', 'Realistic Practical'],
            ['Risk Taker', 'Play It Safe'],
            ['Spontaneous Plans', 'Organized Schedule'],
            ['Minimalist Lifestyle', 'Collector of Things'],
            ['Digital Everything', 'Physical Paper'],
            ['Cutting Edge Tech', 'Proven Reliable Old'],
            ['Fix When Broken', 'Upgrade Constantly'],
            ['Repair and Reuse', 'Buy New Replace'],
            ['Rent Your Home', 'Own Property'],
            ['Urban Apartment', 'Suburban House'],
            ['Downtown Condo', 'Rural Farmhouse'],
            ['Modern Architecture', 'Historic Character'],
            ['Open Floor Plan', 'Separate Rooms'],
            ['Minimalist Decor', 'Cozy Cluttered'],
            ['Smart Home Automation', 'Manual Everything'],
            ['Security Cameras Everywhere', 'Privacy No Cameras'],
            ['HOA Community', 'No Rules Freedom'],
            ['Single Forever', 'Married Forever'],
            ['No Kids Ever', 'Big Family'],
            ['Adopt Children', 'Biological Children'],
            ['Have Twins', 'Have Singles'],
            ['Young Parents', 'Older Mature Parents'],
            ['Strict Parent', 'Relaxed Parent'],
            ['Homeschool Kids', 'Public School'],
            ['Private School Expensive', 'Public School Free'],
            ['Kids Play Outside', 'Kids Play Inside'],
            ['Limit Screen Time', 'Allow Electronics'],

            // Beliefs & Philosophy - What you believe
            ['Believe in Destiny', 'Create Your Path'],
            ['Everything Happens for Reason', 'Random Chaos'],
            ['Aliens Exist', 'Humans Alone'],
            ['Life After Death', 'Nothing After'],
            ['Ghosts Are Real', 'All in Mind'],
            ['Magic Could Exist', 'Pure Science Only'],
            ['Multiverse Theory', 'Single Universe'],
            ['Simulation Theory', 'Base Reality'],
            ['Time is Linear', 'Time is Illusion'],
            ['Free Will Exists', 'Everything Predetermined'],
            ['Consciousness After Death', 'Brain Creates Consciousness'],
            ['Soul Reincarnation', 'One Life Only'],
            ['Karma Is Real', 'Actions Have No Cosmic Consequence'],
            ['Astrology Affects Life', 'Stars Mean Nothing'],
            ['Lucky Numbers', 'All Numbers Equal'],
            ['Manifestation Works', 'Action Creates Results'],
            ['Universe Sends Signs', 'Confirmation Bias'],
            ['Everything Connected', 'Everything Separate'],
            ['Spiritual Energy', 'Physical Matter Only'],
            ['Chakras and Auras', 'No Energy Fields'],

            // Nature & Weather - The elements
            ['Summer Heat', 'Winter Cold'],
            ['Spring Flowers', 'Fall Leaves'],
            ['Sunny Days', 'Rainy Days'],
            ['Snow Day', 'Beach Day'],
            ['Thunderstorm', 'Gentle Rain'],
            ['Hurricane Adventure', 'Tornado Shelter'],
            ['Desert Dry Heat', 'Humid Tropical'],
            ['Constant 75°F', 'All Four Seasons'],
            ['Eternal Daylight', 'Peaceful Darkness'],
            ['Live Near Equator', 'Live Near Poles'],
            ['Ocean View', 'Mountain View'],
            ['Forest Trees', 'Open Plains'],
            ['Waterfall', 'Desert Dunes'],
            ['Tropical Island', 'Arctic Tundra'],
            ['Volcano', 'Glacier'],
            ['Cave Exploring', 'Skyscraper Views'],
            ['Natural Hot Spring', 'Ice Bath'],
            ['Sunrise Watcher', 'Sunset Lover'],
            ['Full Moon', 'New Moon Stars'],
            ['Solar Eclipse', 'Lunar Eclipse'],

            // Life Philosophy - How you think
            ['Work to Live', 'Live to Work'],
            ['Passion Without Pay', 'Money Without Meaning'],
            ['Save for Tomorrow', 'Spend Today'],
            ['Material Possessions', 'Life Experiences'],
            ['Quantity of Things', 'Quality of Moments'],
            ['Hustle Culture', 'Work-Life Balance'],
            ['Climb Corporate Ladder', 'Stay Comfortable Level'],
            ['More Responsibility', 'Less Stress'],
            ['Lead Others', 'Work Alone'],
            ['Public Recognition', 'Private Satisfaction'],
            ['Compete With Others', 'Compete With Self'],
            ['Compare to Others', 'Compare to Past Self'],
            ['Seek External Validation', 'Trust Self Worth'],
            ['Please Others', 'Please Yourself'],
            ['Fit In', 'Stand Out'],
            ['Follow the Crowd', 'Lead the Way'],
            ['Tradition', 'Innovation'],
            ['Proven Path', 'Uncharted Territory'],
            ['Security', 'Adventure'],
            ['Comfort Zone', 'Growth Zone'],

            // Health & Fitness - Physical wellness
            ['Morning Workout', 'Evening Workout'],
            ['Cardio Running', 'Strength Training'],
            ['Gym Membership', 'Home Workouts'],
            ['Personal Trainer', 'YouTube Videos'],
            ['Group Fitness Class', 'Solo Exercise'],
            ['Weights and Machines', 'Bodyweight Only'],
            ['CrossFit Intense', 'Gentle Stretching'],
            ['High Intensity Interval', 'Steady State Cardio'],
            ['Track Macros Strictly', 'Intuitive Eating'],
            ['Meal Plan Prep', 'Eat What You Want'],
            ['Count Calories', 'Listen to Hunger'],
            ['Protein Shakes', 'Real Food Only'],
            ['Supplements', 'Natural Foods'],
            ['Organic Everything', 'Regular Groceries'],
            ['Plant-Based Diet', 'Omnivore Diet'],
            ['Intermittent Fasting', 'Eat Frequently'],
            ['Keto Low Carb', 'High Carb Diet'],
            ['Paleo Diet', 'Modern Foods'],
            ['Raw Food', 'Cooked Meals'],
            ['Juice Cleanse', 'Balanced Meals'],

            // Daily Routines - Everyday life
            ['Early Morning Routine', 'Sleep In Late'],
            ['Cold Shower', 'Hot Shower'],
            ['Long Bath', 'Quick Shower'],
            ['Electric Toothbrush', 'Manual Brush'],
            ['Extensive Skincare', 'Soap and Water'],
            ['Hair Styled Daily', 'Natural Air Dry'],
            ['Wear Perfume/Cologne', 'Natural Scent'],
            ['Matching Socks', 'Mismatched Socks'],
            ['Iron Clothes', 'Wrinkled Casual'],
            ['Organized Closet', 'Messy Pile'],
            ['Make Bed Daily', 'Leave It Messy'],
            ['Clean As You Go', 'Deep Clean Weekly'],
            ['Minimalist Space', 'Decorated Cozy'],
            ['Everything Has Place', 'Organized Chaos'],
            ['Label Everything', 'Remember Location'],
            ['Digital Calendar', 'Paper Planner'],
            ['To-Do List Apps', 'Mental Notes'],
            ['Detailed Planning', 'Go With Flow'],
            ['5 Year Plan', 'Present Moment'],
            ['Track Everything', 'Live Freely'],

            // Drinks & Beverages - What you sip
            ['Iced Coffee', 'Hot Coffee'],
            ['Black Coffee', 'Sweet Latte'],
            ['Expensive Coffee Shop', 'Home Brewed'],
            ['Energy Drinks', 'Natural Energy'],
            ['Soda Pop', 'Sparkling Water'],
            ['Sweet Tea', 'Unsweetened'],
            ['Alcohol Socially', 'Never Drink'],
            ['Wine Connoisseur', 'Beer Enthusiast'],
            ['Mixed Drinks', 'Straight Shots'],
            ['Drink to Relax', 'Stay Sober'],
            ['Party Drinking', 'Casual Sipping'],
            ['Craft Beer', 'Cheap Beer'],
            ['Red Wine', 'White Wine'],
            ['Champagne Celebration', 'Whiskey Neat'],
            ['Tequila Shots', 'Vodka Drinks'],
            ['Rum and Coke', 'Gin and Tonic'],
            ['Margarita', 'Mojito'],
            ['Bloody Mary', 'Mimosa'],
            ['Irish Coffee', 'Espresso Martini'],
            ['Never Hungover', 'Worth The Hangover']
        ];

        this.customPrompts = [];
        this.loadFromStorage();
    }

    loadFromStorage() {
        const stored = localStorage.getItem('customPrompts');
        if (stored) {
            try {
                this.customPrompts = JSON.parse(stored);
            } catch (e) {
                console.error('Failed to load custom prompts:', e);
                this.customPrompts = [];
            }
        }
    }

    saveToStorage() {
        localStorage.setItem('customPrompts', JSON.stringify(this.customPrompts));
    }

    getAllPrompts() {
        return [...this.customPrompts, ...this.defaultPrompts];
    }

    // Automatically selects RANDOM prompts - no configuration needed!
    getRandomPrompts(count = 3) {
        const all = this.getAllPrompts();
        const selected = [];
        const usedIndices = new Set();

        while (selected.length < count && selected.length < all.length) {
            const index = Math.floor(Math.random() * all.length);
            if (!usedIndices.has(index)) {
                usedIndices.add(index);
                selected.push({
                    option1: all[index][0],
                    option2: all[index][1]
                });
            }
        }

        return selected;
    }

    addPrompt(option1, option2) {
        this.customPrompts.push([option1, option2]);
        this.saveToStorage();
    }

    removePrompt(index) {
        if (index >= 0 && index < this.customPrompts.length) {
            this.customPrompts.splice(index, 1);
            this.saveToStorage();
        }
    }

    updatePrompt(index, option1, option2) {
        if (index >= 0 && index < this.customPrompts.length) {
            this.customPrompts[index] = [option1, option2];
            this.saveToStorage();
        }
    }

    resetToDefaults() {
        this.customPrompts = [];
        this.saveToStorage();
    }

    importPrompts(promptsArray) {
        // Format: [["opt1", "opt2"], ["opt3", "opt4"], ...]
        this.customPrompts = promptsArray;
        this.saveToStorage();
    }

    exportPrompts() {
        return JSON.stringify(this.getAllPrompts(), null, 2);
    }
}
